# -*- coding: utf-8 -*-
"""01.시각화문제해결.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UR4RhkaeRTsJwbZ7oesti79-T4-ncwA4

# 시각화문제 해결
"""

#시각화 모듈
import matplotlib.pyplot as plt

#나눔폰트 설치 (Nanum)
!sudo apt-get install -y fonts-nanum
!sodo fc-cache -fv
!rm ~/.cache/matplotlib -rf

#matplotlib의 폰트를 Nanum 폰트로 지정
plt.rc('font', family="NanumBarungothic")

from google.colab import drive
drive.mount('/content/drive')

fp = open('/content/drive/MyDrive/python01/지역평균기온.txt','r', encoding = 'utf-8')
data = fp.readlines()
fp.close()
data

dt = {} #반 딕셔너리 만들기

for line in data:
  line = line.replace("\n", "")
  #print(line)
  items=line.split(',')
  #print(items)
  dt[items[0]] = items[1]

print(type(dt))
dt

x = list(dt.keys())
y = list(dt.values())

print(x)
print(y)

plt.plot(x,y,'o--', color = 'skyblue')

plt.title('지역별 평균기온')
plt.xlabel('도시')
plt.ylabel('온도')

for i in range(0, len(x)):
  plt.text(i, y[i], y[i], ha='canter')

plt.show()

#해당지역의 평균기온을 알려주는 프로그램을 추가하시오.
#- 단, 지역입력에 q가 입력되면, 종료

while True:
  m = int (input())
  for i in data:
    if i==dt(i):
      print(m)
    else m =='q':
      break

answer=""
while True:
	answer=input()
	if answer=="q":
		break
	print(answer)